version: "3.4"

x-logging:
    &logging
    driver: "json-file"
    options:
      max-size: "2G"
      tag: "{% raw %}{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}{% endraw %}"

services:
  traefik:
    image: "traefik:v2.6.6"
    container_name: "traefik"
    restart: always
    command:
        ## TLS challenge
      # - "--log.level=DEBUG"
      # - "--certificatesresolvers.mytlschallenge.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      - "--certificatesresolvers.mytlschallenge.acme.email=me@robinopletal.com"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--providers.file.directory=/etc/traefik/dynamic_conf"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./tools/traefik/config.yml:/etc/traefik/dynamic_conf/conf.yml:ro"
      - "./letsencrypt:/letsencrypt"
    logging: *logging

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    expose:
    - "9090"
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./.prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    logging: *logging
    depends_on:
      - node_exporter

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    expose:
      - 9100
    command:
      - '--path.rootfs=/host'
    pid: host
    volumes:
      - '/:/host:ro,rslave'
    logging: *logging

  promtail:
    container_name: promtail
    image: grafana/promtail:2.5.0
    volumes:
      - /var/lib/docker/:/var/lib/docker:ro
      - ./.promtail/promtail.yml:/etc/promtail/promtail.yml:ro
    command: -config.file=/etc/promtail/promtail.yml
    logging: *logging

  qweebs_dot_com_web:
    depends_on:
      - qweebs_dot_com_db
    build:
      context: ./.qweebs_dot_com
    container_name: "qweebs_dot_com_web"
    volumes:
      - ./.qweebs_dot_com/site_data:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.securityheaders.headers.STSSeconds=31536000"
      - "traefik.http.middlewares.securityheaders.headers.STSIncludeSubdomains=true"
      - "traefik.http.middlewares.securityheaders.headers.STSPreload=true"
      - "traefik.http.routers.qweebs.middlewares=securityheaders@docker"
      - "traefik.http.routers.qweebs.rule=Host(`qweebs.com`,`www.qweebs.com`)"
      - "traefik.http.routers.qweebs.entrypoints=websecure"
      - "traefik.http.routers.qweebs.tls.certresolver=mytlschallenge"
      # discord link redirect
      - "traefik.http.routers.discord_qweebs.rule=Host(`discord.qweebs.com`)"
      - "traefik.http.routers.discord_qweebs.entrypoints=websecure"
      - "traefik.http.routers.discord_qweebs.tls.certresolver=mytlschallenge"
      - "traefik.http.routers.discord_qweebs.middlewares=discord@docker"
      - "traefik.http.middlewares.discord.redirectregex.regex=^https:\\/\\/([^\\/]+)\\/?$$"
      - "traefik.http.middlewares.discord.redirectregex.replacement=https://discord.com/invite/cmjMM9Ccq3"
    restart: always
    environment:
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WC_GZD_ENCRYPTION_KEY', '{{ qweebs_g2d_enc_key }}' );
      WORDPRESS_DB_HOST: qweebs_dot_com_db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: "{{ mysql_password_qweebs }}"
      WORDPRESS_DB_NAME: wordpress
    logging: *logging

  qweebs_dot_com_db:
    image: mariadb:10.10
    volumes:
      - ./.qweebs_dot_com/db_data:/var/lib/mysql
    container_name: "qweebs_dot_com_db"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "{{ mysql_root_password_qweebs }}"
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: "{{ mysql_password_qweebs }}"
    logging: *logging

  backup:
    image: aveltens/wordpress-backup
    container_name: "qweebs_backup"
    restart: always
    volumes:
     - ./backups:/backups
     - ./.qweebs_dot_com/site_data:/var/www/html:ro
    depends_on:
     - qweebs_dot_com_db
    environment:
      MYSQL_ENV_MYSQL_HOST: qweebs_dot_com_db
      MYSQL_ENV_MYSQL_DATABASE: wordpress
      MYSQL_ENV_MYSQL_USER: wordpress
      MYSQL_ENV_MYSQL_PASSWORD: "{{ mysql_password_qweebs }}"
      MYSQL_PORT_3306_TCP_PORT: 3306
      CLEANUP_OLDER_THAN: 7
    logging: *logging

volumes:
  qweebs_dot_com_db:
  promtail:
  backups:
  files_backup:
